on:

  repository_dispatch:
    # trigger from R via:
    # gh::gh("POST /repos/:owner/:repo/dispatches", owner = "Milano-R", repo = "erum2020-covidr-contest", event_type = "cleanup-utterances")
    types: [cleanup-utterances]

  schedule:
    # every 12 h
    - cron: '0 3/12 * * *'

name: Cleanup comments

jobs:
  clenup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup version-stable R 3.6.3
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
        env:
          CRAN: https://mran.microsoft.com/snapshot/2020-04-12
      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Cleanup extra comments to utterances voting issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source("contest/_tools/utterances-issues.R")
          cleanup_utterances_comments(
            owner = "Milano-R",
            repo = "erum2020-covidr-contest",
            site = "https://milano-r.github.io/erum2020-covidr-contest",
            dry_run = TRUE
          )
        shell: Rscript {0}
